fail_fast: true
repos:
  - repo: local
    hooks:
      - id: ruff_check
        name: ruff_check
        language: system
        files: "^(?:mysite|tests)/"
        exclude: "migrations"
        types: [python]
        entry: ruff
        args: ["check"]

      - id: ruff_check_fix
        name: ruff_check_fix
        language: system
        files: "^(?:mysite|tests)/"
        exclude: "migrations"
        types: [python]
        entry: ruff
        args: ["check", "--fix"]

      - id: ruff_format
        name: ruff_format
        language: system
        files: "^(?:mysite|tests)/"
        exclude: "migrations"
        types: [python]
        entry: ruff
        args: ["format"]

      - id: pylint
        name: pylint
        language: system
        files: "^(?:mysite|tests)/"
        exclude: "migrations"
        types: [python]
        entry: pylint
        args: ["tests", "mysite"]

      - id: mypy
        name: mypy
        language: system
        files: "^(?:mysite|tests)/"
        exclude: "migrations"
        types: [python]
        entry: mypy
        args: ["--install-types", "--check-untyped-defs"]

      - id: pytest
        name: pytest
        language: system
        files: "^(?:tests)/"
        exclude: "migrations"
        types: [python]
        entry: pytest
